### PR TITLE
First attempt to add markdown support

### PR DESCRIPTION
**Pull request by Norbiros**
# Idea
I think we can add markdown support for aviate - users can add for example bold text.

# How to use it in aviate?

Just add tags like `**`, `*`, `_`, `__`, `[](<url>)`

# ToDo:
- [ ] Test it
- [ ] Show style in preview
- [ ] Maybe move markdown function to run function

# How to use it in extensions?
```js
var rules = [
  //bold, italics and underline rules
  [/\*\*\s?([^\n]+)\*\*/g, (remove ? "" : "<b>$1</b>")],
  [/__([^_]+)__/g, (remove ? "" : "<u>$1</u>")],
  [/_([^_`]+)_/g, (remove ? "" : "<i>$1</i>")],
  [/\*\s?([^\n]+)\*/g, (remove ? "" : "<i>$1</i>")],
  
  //links
  [
    /\[([^\]]+)\]\(([^)]+)\)/g,
    (remove ? "" : '<a href="$2">$1</a>'),
  ],
];

let parseText = await fetch(`https://aviateapp.eu.org/api/${username}?style=true`)).json()
parseText = escapeHTML(parseText); // escapeHTML function is in SA
rules.forEach(([rule, template]) => {
  parseText = parseText.replace(rule, template)
})
parseText = parseText.replace( );
statusEl.innerHTML = parseText;
```

@MystPi can you please accept this, so I can test it on vercel?

### CODE REVIEW

**Comment by MystPi** [comment]
I think the best option would be to let the fetcher implement any styling that they want. Statuses are plain text and should be independent of styling.

**Comment by Norbiros** [comment]
> I think the best option would be to let the fetcher implement any styling that they want. Statuses are plain text and should be independent of styling.

1. But how users can know about styles then?
2. What if one extension uses markdown, and another their own system?
3. What if specific extension doesn't support styles? Why it someone should implement parser, that just removes styles?
4. It is new great function for aviate (another reason to use it instead of ocular)

**Comment by MystPi** [comment]
> > I think the best option would be to let the fetcher implement any styling that they want. Statuses are plain text and should be independent of styling.
> 
> 1. But how users can know about styles then?
> 2. What if one extension uses markdown, and another their own system?
> 3. What if specific extension doesn't support styles? Why it someone should implement parser, that just removes styles?
> 4. It is new great function for aviate (another reason to use it instead of ocular)
> 
> You didn't enable vercel, or it has build error?

Allowing HTML in statuses (even if it's converted to markdown) is a huge security risk. For example, `**hi** <script>alert("Hello!")</script` would become `<b>hi</b> <script>alert("Hello!")</script>`, meaning people could put all sorts of malicious JavaScript in their status which would get run on every client. Statuses aren't even meant for styling in the first place, so even though this is a cool idea, I don't think it's a good idea right now.

**Comment by Norbiros** [comment]
> > > I think the best option would be to let the fetcher implement any styling that they want. Statuses are plain text and should be independent of styling.
> > 
> > 
> > 
> > 1. But how users can know about styles then?
> > 2. What if one extension uses markdown, and another their own system?
> > 3. What if specific extension doesn't support styles? Why it someone should implement parser, that just removes styles?
> > 4. It is new great function for aviate (another reason to use it instead of ocular)
> > 
> > You didn't enable vercel, or it has build error?
> 
> Allowing HTML in statuses (even if it's converted to markdown) is a huge security risk. For example, `**hi** <script>alert("Hello!")</script` would become `<b>hi</b> <script>alert("Hello!")</script>`, meaning people could put all sorts of malicious JavaScript in their status which would get run on every client. Statuses aren't even meant for styling in the first place, so even though this is a cool idea, I don't think it's a good idea right now.

Because of that we have [auto escaper](
https://github.com/ScratchAddons/ScratchAddons/blob/edc8e11efa6a090bd0ab2eba215694b16c12efad/libraries/common/cs/autoescaper.js).

I am talking about security with apple, so don't worry.

Why statuses aren't meant for styling? What with for example links? 

> It is new great function for aviate (another reason to use it instead of ocular)

**Comment by Norbiros** [comment]
I tested escapeHTML() function, with `<script>` and other tags, and they don't work (so everything works great).

**Comment by MystPi** [comment]
Even with escaping, there is still the possibility of workarounds (there always are), and, as I said before, statuses aren't for styling. Sorry for turning down your PR, but you can add a different type of component if you want. 😿

**Pull request closed without merging**
