### PR TITLE
Add corny dad jokes from the internet

### PR DESCRIPTION
**Pull request by Adzboy**
Exactly what it says on the tin

### CODE REVIEW

**Comment by Adzboy** [comment]
I will update the dashboard text

**Comment by MystPi** [comment]
It looks like a lot of the jokes have syntax errors in them, and there aren't any commas after each item.

**Comment by Adzboy** [comment]
> It looks like a lot of the jokes have syntax errors in them, and there aren't any commas after each item.

Yeah, that's why I've kept this a draft. I'm fixing it up rn

**Comment by MystPi** [comment]
> > It looks like a lot of the jokes have syntax errors in them, and there aren't any commas after each item.
> 
> Yeah, that's why I've kept this a draft. I'm fixing it up rn
> 
> Which have the syntax errors in?

The ones with nested quotes that haven't been escaped. E.g., "hello "there" world".

**Comment by Adzboy** [comment]
> > > It looks like a lot of the jokes have syntax errors in them, and there aren't any commas after each item.
> > 
> > 
> > Yeah, that's why I've kept this a draft. I'm fixing it up rn
> > Which have the syntax errors in?
> 
> The ones with nested quotes that haven't been escaped. E.g., "hello "there" world".

Idk how to do that lol. I'll just leave it, I suppose

**Comment by MystPi** [comment]
> > > > It looks like a lot of the jokes have syntax errors in them, and there aren't any commas after each item.
> > > 
> > > 
> > > Yeah, that's why I've kept this a draft. I'm fixing it up rn
> > > Which have the syntax errors in?
> > 
> > 
> > The ones with nested quotes that haven't been escaped. E.g., "hello "there" world".
> 
> Idk how to do that lol. I'll just leave it, I suppose

Add a backslash \ in front of the nested quotes: "hello \\"there\\" world".

**Comment by Adzboy** [comment]
> > > > > It looks like a lot of the jokes have syntax errors in them, and there aren't any commas after each item.
> > > > 
> > > > 
> > > > Yeah, that's why I've kept this a draft. I'm fixing it up rn
> > > > Which have the syntax errors in?
> > > 
> > > 
> > > The ones with nested quotes that haven't been escaped. E.g., "hello "there" world".
> > 
> > 
> > Idk how to do that lol. I'll just leave it, I suppose
> 
> Add a backslash \ in front of the nested quotes: "hello \"there\" world".

Is that right?

**Comment by MystPi** [comment]
I've fixed it for you. Thanks for your contribution!

**Pull request merged**
